# Generated by Django 5.2.6 on 2026-09-10 12:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('work', 'Work'), ('education', 'Education')], default='work', max_length=16)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, help_text='Leave empty if this is current.', null=True)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('org_fa', models.CharField(max_length=140)),
                ('org_en', models.CharField(blank=True, max_length=140)),
                ('org_de', models.CharField(blank=True, max_length=140)),
                ('role_fa', models.CharField(max_length=140)),
                ('role_en', models.CharField(blank=True, max_length=140)),
                ('role_de', models.CharField(blank=True, max_length=140)),
                ('description_fa', models.TextField(help_text='Markdown. What you actually did.')),
                ('description_en', models.TextField(blank=True, help_text='Markdown. What you actually did.')),
                ('description_de', models.TextField(blank=True, help_text='Markdown. What you actually did.')),
                ('location_fa', models.CharField(max_length=80)),
                ('location_en', models.CharField(blank=True, max_length=80)),
                ('location_de', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ('order', '-start'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('body', models.TextField()),
                ('language', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_handled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, upload_to='profile/')),
                ('resume_file', models.FileField(blank=True, upload_to='profile/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('telegram', models.CharField(blank=True, help_text='username, no @', max_length=64)),
                ('github', models.CharField(blank=True, max_length=64)),
                ('linkedin', models.CharField(blank=True, max_length=120)),
                ('twitter', models.CharField(blank=True, max_length=64)),
                ('website', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('full_name_fa', models.CharField(max_length=120)),
                ('full_name_en', models.CharField(blank=True, max_length=120)),
                ('full_name_de', models.CharField(blank=True, max_length=120)),
                ('headline_fa', models.CharField(help_text='One line under the name.', max_length=160)),
                ('headline_en', models.CharField(blank=True, help_text='One line under the name.', max_length=160)),
                ('headline_de', models.CharField(blank=True, help_text='One line under the name.', max_length=160)),
                ('intro_fa', models.TextField(help_text='Two or three sentences on the home hero.')),
                ('intro_en', models.TextField(blank=True, help_text='Two or three sentences on the home hero.')),
                ('intro_de', models.TextField(blank=True, help_text='Two or three sentences on the home hero.')),
                ('bio_fa', models.TextField(help_text='Long form, Markdown. Shown on /about/.')),
                ('bio_en', models.TextField(blank=True, help_text='Long form, Markdown. Shown on /about/.')),
                ('bio_de', models.TextField(blank=True, help_text='Long form, Markdown. Shown on /about/.')),
                ('location_fa', models.CharField(max_length=80)),
                ('location_en', models.CharField(blank=True, max_length=80)),
                ('location_de', models.CharField(blank=True, max_length=80)),
                ('now_fa', models.CharField(help_text='What you are working on right now.', max_length=200)),
                ('now_en', models.CharField(blank=True, help_text='What you are working on right now.', max_length=200)),
                ('now_de', models.CharField(blank=True, help_text='What you are working on right now.', max_length=200)),
                ('availability_fa', models.CharField(help_text='e.g. open to work', max_length=80)),
                ('availability_en', models.CharField(blank=True, help_text='e.g. open to work', max_length=80)),
                ('availability_de', models.CharField(blank=True, help_text='e.g. open to work', max_length=80)),
            ],
            options={
                'verbose_name': 'profile',
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name_fa', models.CharField(max_length=80)),
                ('name_en', models.CharField(blank=True, max_length=80)),
                ('name_de', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name_fa', models.CharField(max_length=60)),
                ('name_en', models.CharField(blank=True, max_length=60)),
                ('name_de', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Technology names stay Latin in every language.', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False, help_text='Shown in the home hero strip.')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='content.skillgroup')),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('stack', models.CharField(blank=True, help_text='Comma separated, Latin, e.g. Django, Postgres', max_length=200)),
                ('cover', models.ImageField(blank=True, upload_to='projects/')),
                ('repo_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Appears on the home page.')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title_fa', models.CharField(max_length=140)),
                ('title_en', models.CharField(blank=True, max_length=140)),
                ('title_de', models.CharField(blank=True, max_length=140)),
                ('summary_fa', models.CharField(help_text='One sentence, shown on the card.', max_length=240)),
                ('summary_en', models.CharField(blank=True, help_text='One sentence, shown on the card.', max_length=240)),
                ('summary_de', models.CharField(blank=True, help_text='One sentence, shown on the card.', max_length=240)),
                ('role_fa', models.CharField(max_length=120)),
                ('role_en', models.CharField(blank=True, max_length=120)),
                ('role_de', models.CharField(blank=True, max_length=120)),
                ('problem_fa', models.TextField(help_text='Markdown. What needed solving.')),
                ('problem_en', models.TextField(blank=True, help_text='Markdown. What needed solving.')),
                ('problem_de', models.TextField(blank=True, help_text='Markdown. What needed solving.')),
                ('body_fa', models.TextField(help_text='Markdown. What you built and why.')),
                ('body_en', models.TextField(blank=True, help_text='Markdown. What you built and why.')),
                ('body_de', models.TextField(blank=True, help_text='Markdown. What you built and why.')),
                ('outcome_fa', models.CharField(help_text='The result, in one line.', max_length=240)),
                ('outcome_en', models.CharField(blank=True, help_text='The result, in one line.', max_length=240)),
                ('outcome_de', models.CharField(blank=True, help_text='The result, in one line.', max_length=240)),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='content.tag')),
            ],
            options={
                'ordering': ('order', '-year', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('cover', models.ImageField(blank=True, upload_to='posts/')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('title_fa', models.CharField(max_length=180)),
                ('title_en', models.CharField(blank=True, max_length=180)),
                ('title_de', models.CharField(blank=True, max_length=180)),
                ('excerpt_fa', models.CharField(max_length=280)),
                ('excerpt_en', models.CharField(blank=True, max_length=280)),
                ('excerpt_de', models.CharField(blank=True, max_length=280)),
                ('body_fa', models.TextField(help_text='Markdown.')),
                ('body_en', models.TextField(blank=True, help_text='Markdown.')),
                ('body_de', models.TextField(blank=True, help_text='Markdown.')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='content.tag')),
            ],
            options={
                'ordering': ('-published_at', '-pk'),
            },
        ),
    ]
