# Generated by Django 5.2.6 on 2026-09-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='languages_de',
            field=models.CharField(blank=True, default='', help_text="Spoken languages and levels, e.g. 'Persian native · English C1 · German A1'. A German CV is expected to state these; the résumé page shows it in the fact bar.", max_length=160),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages_en',
            field=models.CharField(blank=True, default='', help_text="Spoken languages and levels, e.g. 'Persian native · English C1 · German A1'. A German CV is expected to state these; the résumé page shows it in the fact bar.", max_length=160),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages_fa',
            field=models.CharField(default='', help_text="Spoken languages and levels, e.g. 'Persian native · English C1 · German A1'. A German CV is expected to state these; the résumé page shows it in the fact bar.", max_length=160),
        ),
    ]
