# Generated by Django 5.2.6 on 2026-09-13 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_profile_languages_de_profile_languages_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('layers', 'layers'), ('clock', 'clock'), ('target', 'target'), ('briefcase', 'briefcase'), ('code', 'code'), ('database', 'database'), ('sparkle', 'sparkle'), ('check', 'check')], default='sparkle', max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title_fa', models.CharField(max_length=80)),
                ('title_en', models.CharField(blank=True, max_length=80)),
                ('title_de', models.CharField(blank=True, max_length=80)),
                ('body_fa', models.CharField(max_length=280)),
                ('body_en', models.CharField(blank=True, max_length=280)),
                ('body_de', models.CharField(blank=True, max_length=280)),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='original_url',
            field=models.URLField(blank=True, help_text='Where this was first published — a LinkedIn post, X, Virgool, Medium. Shown under the post as a link to the original.', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='offer_body_de',
            field=models.TextField(blank=True, default='', help_text='Markdown. The long form on /services/ — what you build, how a project runs.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='offer_body_en',
            field=models.TextField(blank=True, default='', help_text='Markdown. The long form on /services/ — what you build, how a project runs.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='offer_body_fa',
            field=models.TextField(blank=True, default='', help_text='Markdown. The long form on /services/ — what you build, how a project runs.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='offer_lede_de',
            field=models.TextField(blank=True, default='', help_text='One or two sentences under it.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='offer_lede_en',
            field=models.TextField(blank=True, default='', help_text='One or two sentences under it.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='offer_lede_fa',
            field=models.TextField(blank=True, default='', help_text='One or two sentences under it.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='offer_title_de',
            field=models.CharField(blank=True, default='', help_text='Headline of the services offer. Empty hides the page, the nav link and the home band.', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='offer_title_en',
            field=models.CharField(blank=True, default='', help_text='Headline of the services offer. Empty hides the page, the nav link and the home band.', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='offer_title_fa',
            field=models.CharField(blank=True, default='', help_text='Headline of the services offer. Empty hides the page, the nav link and the home band.', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='og_image',
            field=models.ImageField(blank=True, help_text='The picture a shared link shows on LinkedIn, Telegram, WhatsApp or X. 1200×630 px. Falls back to the avatar.', upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='seo_description_de',
            field=models.CharField(blank=True, default='', help_text='The home page meta description — the two lines under the link in search results. 120–160 characters. Falls back to the intro.', max_length=170),
        ),
        migrations.AddField(
            model_name='profile',
            name='seo_description_en',
            field=models.CharField(blank=True, default='', help_text='The home page meta description — the two lines under the link in search results. 120–160 characters. Falls back to the intro.', max_length=170),
        ),
        migrations.AddField(
            model_name='profile',
            name='seo_description_fa',
            field=models.CharField(blank=True, default='', help_text='The home page meta description — the two lines under the link in search results. 120–160 characters. Falls back to the intro.', max_length=170),
        ),
        migrations.AddField(
            model_name='profile',
            name='seo_title_de',
            field=models.CharField(blank=True, default='', help_text='The home page <title>, up to ~60 characters: name plus what you do. Falls back to the name.', max_length=70),
        ),
        migrations.AddField(
            model_name='profile',
            name='seo_title_en',
            field=models.CharField(blank=True, default='', help_text='The home page <title>, up to ~60 characters: name plus what you do. Falls back to the name.', max_length=70),
        ),
        migrations.AddField(
            model_name='profile',
            name='seo_title_fa',
            field=models.CharField(blank=True, default='', help_text='The home page <title>, up to ~60 characters: name plus what you do. Falls back to the name.', max_length=70),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_fa',
            field=models.TextField(blank=True, help_text='Markdown. What you actually did.'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location_fa',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_de',
            field=models.TextField(blank=True, help_text='Markdown. A line break stays a line break, so text pasted from LinkedIn keeps its shape. ## heading · **bold** · [text](https://…) for a link · a bare https://… link works too · ![description](/media/…) for an image — upload images at the bottom of this page and copy their line from there.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_en',
            field=models.TextField(blank=True, help_text='Markdown. A line break stays a line break, so text pasted from LinkedIn keeps its shape. ## heading · **bold** · [text](https://…) for a link · a bare https://… link works too · ![description](/media/…) for an image — upload images at the bottom of this page and copy their line from there.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_fa',
            field=models.TextField(blank=True, help_text='Markdown. A line break stays a line break, so text pasted from LinkedIn keeps its shape. ## heading · **bold** · [text](https://…) for a link · a bare https://… link works too · ![description](/media/…) for an image — upload images at the bottom of this page and copy their line from there.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, help_text='Shown above the post and as the picture when the link is shared. 1200×630 px reads best.', upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt_de',
            field=models.CharField(blank=True, help_text='One or two sentences. Shown in the list and used as the search result description, so 120–160 characters reads best.', max_length=280),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt_en',
            field=models.CharField(blank=True, help_text='One or two sentences. Shown in the list and used as the search result description, so 120–160 characters reads best.', max_length=280),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt_fa',
            field=models.CharField(blank=True, help_text='One or two sentences. Shown in the list and used as the search result description, so 120–160 characters reads best.', max_length=280),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='The address: /blog/<slug>/. Latin, lowercase, hyphens — e.g. sql-server-locking. Keep it stable once published.', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_fa',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='profile',
            name='availability_fa',
            field=models.CharField(blank=True, help_text='e.g. open to work', max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio_fa',
            field=models.TextField(blank=True, help_text='Long form, Markdown. Shown on /about/.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages_fa',
            field=models.CharField(blank=True, default='', help_text="Spoken languages and levels, e.g. 'Persian native · English C1 · German A1'. A German CV is expected to state these; the résumé page shows it in the fact bar.", max_length=160),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location_fa',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='now_fa',
            field=models.CharField(blank=True, help_text='What you are working on right now.', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='body_fa',
            field=models.TextField(blank=True, help_text='Markdown. What you built and why.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='outcome_fa',
            field=models.CharField(blank=True, help_text='The result, in one line.', max_length=240),
        ),
        migrations.AlterField(
            model_name='project',
            name='problem_fa',
            field=models.TextField(blank=True, help_text='Markdown. What needed solving.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='role_fa',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/body/')),
                ('alt', models.CharField(blank=True, help_text='What the image shows, in a few words. Read aloud by screen readers and by Google Images.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.post')),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
    ]
