# Generated by Django 5.2.6 on 2026-09-21 16:39

import apps.content.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_message_tracking_and_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='event',
            field=models.CharField(blank=True, choices=[('cancelled', 'لغو توسط درخواست\u200cکننده — cancelled by the visitor')], max_length=16),
        ),
        migrations.AlterField(
            model_name='reply',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ChatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=64)),
                ('phone', models.CharField(help_text='As shared from the messenger, normalised.', max_length=32)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('told_status', models.CharField(blank=True, max_length=16)),
                ('told_reply_id', models.BigIntegerField(default=0)),
                ('awaiting_reply_since', models.DateTimeField(blank=True, null=True)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_link', to='content.message')),
            ],
            options={
                'verbose_name': 'chat link',
            },
        ),
        migrations.CreateModel(
            name='ChatLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.content.models.new_link_token, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('chat_id', models.CharField(blank=True, max_length=64)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_tokens', to='content.message')),
            ],
        ),
    ]
