# Generated by Django 5.2.6 on 2026-09-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_visitor_chat_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(help_text="A picture inside the post's text. Save, then paste the Markdown line beside it where it should appear; the first one is also the shared-link picture when there is no cover.", upload_to='posts/body/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Your portrait: the home page hero, /about/, /resume/ and the business card /card/ — and the shared-link picture while the one below is empty. Square, at least 700×700 px.', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='og_image',
            field=models.ImageField(blank=True, help_text='The picture a shared link shows on LinkedIn, Telegram, WhatsApp or X, for every page without a picture of its own. 1200×630 px. Falls back to the avatar.', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_file',
            field=models.FileField(blank=True, help_text='The file behind every «download résumé» button: the home hero, /resume/ and the footer. PDF. Empty hides the buttons.', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=models.ImageField(blank=True, help_text="The project's card on the home page and /projects/, the top of its own page, and the picture when its link is shared. Landscape, about 1600×1000 px.", upload_to='projects/'),
        ),
    ]
